- type: entity
  id: CitadelBaseContract
  name: Contract
  description: |
    A contract controller entity, manages some given contract.
    You probably shouldn't be seeing this.
  abstract: true
  components:
    - type: Contract
    - type: ContractCriteriaControl
      criteria: {}

- type: entity
  id: CitadelTestingContract
  parent: CitadelBaseContract
  name: Test Contract
  description: A contract that simply requires nobody dies and admin approval.
  noSpawn: true
  components:
    - type: ContractCriteriaControl
      criteria:
        Finalizing:
          - CitadelCriteriaAdminApproval
        Breaching:
          - CitadelCriteriaNoDeaths
